# Teams Analysis

Loads the `teams` table written by `teams_etl.py` and provides basic profiling.

In [1]:
import duckdb, os, glob, json, pandas as pd, plotly.express as px

In [2]:
# Resolve DuckDB database (pick latest mydb*.duckdb if not specified)
db_candidates = sorted(glob.glob('../../data/mydb2024-25*.duckdb'))
db_path = db_candidates[-1] if db_candidates else '../data/mydb.duckdb'
print(f'Using DuckDB database: {db_path}')
con = duckdb.connect(db_path)

Using DuckDB database: ../../data\mydb2024-25.duckdb

In [3]:
# Load teams table
try:
    df_teams = con.execute('SELECT * FROM teams').df()
except Exception as e:
    raise RuntimeError(f'Teams table not found: {e}')
df_teams.head()

,entityId,nameFullLocal,nameFullLatin,codeLocal,codeLatin,externalId
0,fef51771-3952-11ef-97b4-af5c55c3771d,ThSV Eisenach,ThSV Eisenach,EIS,EIS,32
1,feace61d-3952-11ef-ae23-af5c55c3771d,SC DHfK Leipzig,SC DHfK Leipzig,LEI,LEI,13
2,febb3114-3952-11ef-b6f7-af5c55c3771d,TVB Stuttgart,TVB Stuttgart,TVB,TVB,17
3,feb41b46-3952-11ef-9df6-af5c55c3771d,MT Melsungen,MT Melsungen,MTM,MTM,15
4,fe911367-3952-11ef-9131-af5c55c3771d,VfL Gummersbach,VfL Gummersbach,GUM,GUM,7

In [4]:
# Basic stats
print(f'Total teams: {len(df_teams)}')
display(df_teams.describe(include='all').transpose())

Total teams: 18

              count unique                                   top freq
entityId         18     18  fef51771-3952-11ef-97b4-af5c55c3771d    1
nameFullLocal    18     18                         ThSV Eisenach    1
nameFullLatin    18     18                         ThSV Eisenach    1
codeLocal        18     18                                   EIS    1
codeLatin        18     18                                   EIS    1
externalId       18     18                                    32    1

In [ ]:
# Visual: codeLocal / codeLatin uniqueness
cols = [c for c in ['codeLocal','codeLatin'] if c in df_teams.columns]
long = df_teams.melt(value_vars=cols, var_name='code_type', value_name='code').dropna()
px.bar(long.groupby('code_type')['code'].nunique().reset_index(), x='code_type', y='code', title='Unique Codes per Type')

: